#pragma once

#define VIB_VERSION_MAJOR 0
#define VIB_VERSION_MINOR 0
#define VIB_VERSION_PATCH 1

#define VIB_VERSION_STRING_BUILDER_HELPER(x)    #x
#define VIB_VERSION_STRING_BUILDER(x)           VIB_VERSION_STRING_BUILDER_HELPER(x)

#define VIB_VERSION_STRING \
        VIB_VERSION_STRING_BUILDER(VIB_VERSION_MAJOR) "." \
        VIB_VERSION_STRING_BUILDER(VIB_VERSION_MINOR) "." \
        VIB_VERSION_STRING_BUILDER(VIB_VERSION_PATCH)

